_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 0bf2b068-e811-4915-803e-4795c159a51c
name: 'My Boguslav'
mail: mybg@gmail.com
slogan: 'The most beloved city in the world'
page:
  403: ''
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
